name = "app"
target = "javascript"

# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
lustre = ">= 5.6.0 and < 6.0.0"
gleam_regexp = ">= 1.1.1 and < 2.0.0"
phosphor_lustre = ">= 1.0.1 and < 2.0.0"
funtil = ">= 1.1.0 and < 2.0.0"

[dev_dependencies]

# Lustre configuration.
# See: https://hexdocs.pm/lustre_dev_tools/toml-reference.html

[tools.lustre.build]
minify = true
outdir = "./dist"
